[2022-04-18 17:15:24,810] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-18 17:15:24,811] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-04-18 17:15:24,812] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-18 17:15:24,813] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-18 17:15:24,813] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ==dddf"}
[2022-04-18 17:15:24,814] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-04-18 17:15:26,949] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C39EB998C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:15:26,950] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C39EB998C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:15:26,950] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-18 17:15:26,951] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-18 17:15:26,952] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-18 17:17:14,710] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-18 17:17:14,711] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-04-18 17:17:14,712] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-18 17:17:14,713] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-18 17:17:14,713] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ==dddf"}
[2022-04-18 17:17:14,714] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-04-18 17:17:16,731] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C39E67BD48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:17:16,732] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C39E67BD48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:17:16,733] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-18 17:17:16,733] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-18 17:17:16,734] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-18 17:19:29,895] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-18 17:19:29,896] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-04-18 17:19:29,897] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-18 17:19:29,898] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-18 17:19:29,899] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ==dddf"}
[2022-04-18 17:19:29,899] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-04-18 17:19:31,917] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C39F227548>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:19:31,918] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C39F227548>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:19:31,919] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-18 17:19:31,919] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-18 17:19:31,920] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-18 17:36:31,089] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-18 17:36:31,090] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-04-18 17:36:31,091] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-18 17:36:31,091] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-18 17:36:31,092] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-04-18 17:36:31,093] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-04-18 17:36:33,125] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C3A10754C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:36:33,126] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C3A10754C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:36:33,127] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-18 17:36:33,127] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-18 17:36:33,128] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
[2022-04-18 17:44:38,163] [log.py|__console] [line:37] INFO    : ==============================================start==============================================
[2022-04-18 17:44:38,164] [log.py|__console] [line:37] INFO    : 标题:测试一下
[2022-04-18 17:44:38,165] [log.py|__console] [line:37] INFO    : url:http://172.30.22.186:8003/eep_emg/whatsapp/message
[2022-04-18 17:44:38,165] [log.py|__console] [line:37] INFO    : 请求方法:POST
[2022-04-18 17:44:38,166] [log.py|__console] [line:37] INFO    : 请求头:{"Content-Type": "application/json;charset=UTF-8", "Authorization": "BasicY2l0aWMtd2EtdHJpYWw6Y2l0aWNAODkzNQ=="}
[2022-04-18 17:44:38,167] [log.py|__console] [line:37] INFO    : 请求体:{"channel":"whatsapp","to":"85259842833","whatsapp":{"type":"text","text":{"body":"测试"},"preview_url":false}}
[2022-04-18 17:44:40,183] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C3A186B948>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:44:40,184] [log.py|__console] [line:43] ERROR   : HTTPConnectionPool(host='172.30.22.186', port=8003): Max retries exceeded with url: /eep_emg/whatsapp/message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C3A186B948>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-18 17:44:40,184] [log.py|__console] [line:43] ERROR   : 获取响应失败，请检查
[2022-04-18 17:44:40,185] [log.py|__console] [line:43] ERROR   : 最终测试结果:失败
[2022-04-18 17:44:40,186] [log.py|__console] [line:37] INFO    : ==============================================end==============================================
